# Generated by Django 4.1.7 on 2023-03-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variation',
            new_name='Variations',
        ),
    ]
